package cn.net.syzc.analysis.model;

import cn.net.syzc.analysis.model.base.BaseTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Task extends BaseTask<Task> {
	public static final Task dao = new Task().dao();
}
