package cn.net.syzc.analysis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unused"})
public abstract class BaseTask<M extends BaseTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserID(java.lang.Integer UserID) {
		set("UserID", UserID);
	}
	
	public java.lang.Integer getUserID() {
		return getInt("UserID");
	}

	public void setTaskName(java.lang.String TaskName) {
		set("TaskName", TaskName);
	}
	
	public java.lang.String getTaskName() {
		return getStr("TaskName");
	}

	public void setAlgorithmType(java.lang.String AlgorithmType) {
		set("AlgorithmType", AlgorithmType);
	}
	
	public java.lang.String getAlgorithmType() {
		return getStr("AlgorithmType");
	}

	public void setEdgeFile(java.lang.String EdgeFile) {
		set("EdgeFile", EdgeFile);
	}
	
	public java.lang.String getEdgeFile() {
		return getStr("EdgeFile");
	}

	public void setAttriFile(java.lang.String AttriFile) {
		set("AttriFile", AttriFile);
	}
	
	public java.lang.String getAttriFile() {
		return getStr("AttriFile");
	}

	public void setClassFile(java.lang.String ClassFile) {
		set("ClassFile", ClassFile);
	}
	
	public java.lang.String getClassFile() {
		return getStr("ClassFile");
	}

	public void setStartTime(java.util.Date StartTime) {
		set("StartTime", StartTime);
	}
	
	public java.util.Date getStartTime() {
		return get("StartTime");
	}

	public void setEndTime(java.util.Date EndTime) {
		set("EndTime", EndTime);
	}
	
	public java.util.Date getEndTime() {
		return get("EndTime");
	}

	public void setPath(java.lang.String Path) {
		set("Path", Path);
	}
	
	public java.lang.String getPath() {
		return getStr("Path");
	}

	public void setMessages(java.lang.String Messages) {
		set("Messages", Messages);
	}
	
	public java.lang.String getMessages() {
		return getStr("Messages");
	}

}
